name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ${{matrix.runners}}

    strategy:
        matrix:
          runners: [self-hosted,aws-ec2]

    steps:
    - uses: actions/checkout@v4
    - name: delete any existing containers
      run: docker rm -f snippets_container
    - name: Build the Docker image
      run: docker build -t snippets .
    - name: start container
      run: docker run --name snippets_container -p 3001:3001 -d snippets
